jobs:
  test:
    name: Test JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@main
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@main
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@main
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-m2

          '
    - continue-on-error: true
      name: Chmod
      run: chmod +x mvnw
    - continue-on-error: true
      if: ${{ matrix.java == '8' }}
      name: Test with Maven
      run: ./mvnw test -B -Dmaven.test.skip=false
    - continue-on-error: true
      if: ${{ matrix.java != '8' }}
      name: Test with Maven
      run: ./mvnw test -B -Dmaven.test.skip=false -DargLine="--add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.reflect.annotation=ALL-UNNAMED"
    - continue-on-error: true
      name: Maven Build
      run: ./mvnw install -B -V
    - continue-on-error: true
      name: Java Doc
      run: ./mvnw javadoc:javadoc
    strategy:
      fail-fast: false
      matrix:
        distribution:
        - adopt
        java:
        - 8
        - 11
        - 17
        - 21
      max-parallel: 4
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
